from pydantic import BaseModel, Field, UUID4, field_validator
from typing import Optional, Dict, Any
from enum import Enum
from datetime import datetime

class EventType(str, Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    ZONE_ENTER = "ZONE_ENTER"
    ZONE_EXIT = "ZONE_EXIT"
    ZONE_DWELL = "ZONE_DWELL"
    BILLING_QUEUE_JOIN = "BILLING_QUEUE_JOIN"
    REENTRY = "REENTRY"

class ZoneMetadata(BaseModel):
    queue_depth: Optional[int] = Field(None, description="Active queue headcount, primarily for billing cam context")
    sku_zone: Optional[str] = Field(None, description="The specific product category category like SKINCARE, FRAGRANCE")
    session_seq: int = Field(1, description="Increments if a visitor leaves and triggers a Re-entry pattern")

class RetailTelemetryEvent(BaseModel):
    event_id: str = Field(..., description="Unique UUIDv4 per discrete event to guarantee idempotency")
    store_id: str = Field(..., description="Unique string identification for the physical branch location")
    camera_id: str = Field(..., description="Hardware identifier mapping the stream viewpoint context")
    visitor_id: str = Field(..., description="Persistent tracking token generated by ByteTrack/Re-ID layer")
    event_type: EventType = Field(..., description="Enforced action categories defining the state change")
    timestamp: datetime = Field(..., description="ISO-8601 UTC timestamp synced directly from video frame offsets")
    zone_id: Optional[str] = Field(None, description="Identifier of the specific retail store boundary zone")
    dwell_ms: int = Field(0, description="Dwell tracking measurement in milliseconds, defaults to 0")
    is_staff: bool = Field(False, description="Flag identifying employees to filter them out of commercial funnel math")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence floating metric of the bounding tracker box")
    metadata: ZoneMetadata = Field(default_factory=ZoneMetadata)

    @field_validator('event_id')
    @classmethod
    def validate_uuid_string(cls, v: str) -> str:
        """Enforces that the incoming event identifier string is structurally a valid UUID."""
        import uuid
        try:
            uuid.UUID(v)
        except ValueError:
            raise ValueError("event_id field must match a conforming UUIDv4 variant specification")
        return v